name = "PkgToSoftwareBOM"
uuid = "6254a0f9-6143-4104-aa2e-fd339a2830a6"
authors = ["Simon Avery <savery@ieee.org> and contributors"]
version = "0.1.3"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SPDX = "47358f48-d834-4249-91f5-f6185eb3d540"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
SPDX = "0.2.1,0.3"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
