name = "PkgToSoftwareBOM"
uuid = "6254a0f9-6143-4104-aa2e-fd339a2830a6"
authors = ["Simon Avery <savery@ieee.org> and contributors"]
version = "0.1.16"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SPDX = "47358f48-d834-4249-91f5-f6185eb3d540"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
RegistryInstances = "2792f1a3-b283-48e8-9a74-f99dce5104f3"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
LicenseCheck = "726dbf0d-6eb6-41af-b36c-cd770e0f00cc"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Downloads= "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[compat]
SPDX = "0.4"
RegistryInstances = "0.1"
Reexport = "1"
LicenseCheck = "0.2"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
